### ISSUE TITLE
Snippets of code

### ISSUE THREAD

**Issue by brunowego** [gerardmrk/erogen#1]
Hi Gerard,

I'm find your project and some snippets of your code help me in a personal project. I separated the auth part in another service:

```proto
syntax = "proto3";

package auth;

option go_package = "authpb";

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

service AuthService {
  // Unauthenticated requests
  rpc Login(LoginRequest) returns (LoginResponse);

  // Authenticated write requests
  rpc Logout(LogoutRequest) returns (google.protobuf.Empty);

  // Authenticated read requests
  rpc IsAuthenticated(IsAuthenticatedRequest) returns (google.protobuf.BoolValue);
  rpc ValidateToken(ValidateTokenRequest) returns (ValidateTokenResponse);
}

message LoginRequest {
  string identifier = 1;
  AuthIdentifierType identifier_type = 2;
  string password = 3;
  bool remember = 4;
  uint32 remember_for = 5;
  bool fetch_tokens = 6;
}

message LoginResponse {
  bool success = 1;
  TokenPayload payload = 2;
  message TokenPayload {
    string id_token = 1;
    string access_token = 2;
    string refresh_token = 3;
    string token_type = 4;
    string scope = 5;
    int32 expires_in = 6;
  }
}

message LogoutRequest {
  int64 id = 1;
}

message IsAuthenticatedRequest {
  string answer = 1;
}

message ValidateTokenRequest {
  string token = 1;
  Scope scope = 2;
  enum Scope {
    EMAIL_VERIFICATION = 0;
    PASSWORD_RESET = 1;
  }
}

message ValidateTokenResponse {
  bool success = 1;
}

enum AuthIdentifierType {
  UNKNOWN = 0;
  USERNAME = 1;
  EMAIL_ADDRESS = 2;
  MOBILE_NUMBER = 3;
}
```

What you think about this?

**Comment by brunowego** [comment]
The user proto:

```proto
syntax = "proto3";

package user;

option go_package = "userpb";

service UserService {
  // Unauthenticated requests
  rpc Register(RegisterRequest) returns (RegisterResponse);
  rpc ForgotPassword(ForgotPasswordRequest) returns (ForgotPasswordResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  // Authenticated write requests
  rpc ChangeEmail(ChangeEmailRequest) returns (ChangeEmailResponse);
  rpc ChangeUsername(ChangeUsernameRequest) returns (ChangeUsernameResponse);
  rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  // Authenticated read requests
  rpc VerifySecurityQA(VerifySecurityQARequest) returns (VerifySecurityQAResponse);
  rpc User(UserRequest) returns (UserResponse);
  rpc Users(UsersRequest) returns (stream UserResponse);
}

message RegisterRequest {
  string username = 1;
  string email_address = 2;
  string password = 3;
  string accepted_tos_version = 4;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
}

message ForgotPasswordRequest {
  string email_address = 1;
}

message ForgotPasswordResponse {
  bool user_exists = 1;
  bool sendemail_queued = 2;
}

message ResetPasswordRequest {
  int64 user_id = 1;
  string new_password = 2;
}

message ResetPasswordResponse {
  bool success = 1;
  string message = 2;
}

message ChangeEmailRequest {
  int64 id = 1;
  string current_email = 2;
  string new_email = 3;
}

message ChangeEmailResponse {
  bool success = 1;
  string message = 2;
}

message ChangeUsernameRequest {
  int64 id = 1;
  string current_username = 2;
  string new_username = 3;
}

message ChangeUsernameResponse {
  bool success = 1;
  string message = 2;
}

message ChangePasswordRequest {
  int64 id = 1;
  string current_password = 2;
  string new_password = 3;
}

message ChangePasswordResponse {
  bool success = 1;
  string message = 2;
}

message VerifySecurityQARequest {
  string answer = 1;
}

message VerifySecurityQAResponse {
  bool success = 1;
}

message UpdateRequest {
  User user = 1;
}

message UpdateResponse {
  bool success = 1;
  User user = 2;
}

message DeleteRequest {
  int64 id = 1;
}

message DeleteResponse {
  bool success = 1;
}

message UserRequest {
  int64 id = 1;
}

message UserResponse {
  User user = 1;
}

message UsersRequest {
  string filter = 1;
  uint32 count = 2;
  uint32 offset = 3;
}

message User {}
```

**Comment by gerardmrk** [comment]
@brunowego yeah that's a good idea, I didn't think to separate the identity service from the auth service.

Everything in `/proto/*` and `/svc/*` is still incomplete, as I'm more focused on the Terraform aspect right now in `/infra`, I'll revisit the protobuf definitions after I'm done with the tf templates. Feel free to merge it in tho.

**Comment by gerardmrk** [comment]
if you're curious, for reference this is the planned structure for the user service and what the `User` proto message would've looked likke eventually: https://github.com/gerardmrk/erogen/blob/master/docs/user_db_draft.temp.png

And the generated SQL:
https://github.com/gerardmrk/erogen/blob/master/svc/user/migrations/001.init.up.sql

These will not work yet it's still in progress and still needs some polishing up.

**Comment by gerardmrk** [comment]
Also, the reason all the `id` fields are of type string is because I'm planning on using [ULIDs](https://github.com/oklog/ulid) for the user's unique identifier as opposed to an identity key.

**Comment by brunowego** [comment]
> @brunowego yeah that's a good idea, I didn't think to separate the identity service from the auth service.
> 
> Everything in `/proto/*` and `/svc/*` is still incomplete, as I'm more focused on the Terraform aspect right now in `/infra`, I'll revisit the protobuf definitions after I'm done with the tf templates. Feel free to merge it in tho.

Yeah, I understand.



> if you're curious, for reference this is the planned structure for the user service and what the `User` proto message would've looked likke eventually: https://github.com/gerardmrk/erogen/blob/master/docs/user_db_draft.temp.png
> 
> And the generated SQL:
> https://github.com/gerardmrk/erogen/blob/master/svc/user/migrations/001.init.up.sql
> 
> These will not work yet it's still in progress and still needs some polishing up.

I appreciate your knowledge sharing, thanks. Your model is rich in detail.

> Also, the reason all the `id` fields are of type string is because I'm planning on using [ULIDs](https://github.com/oklog/ulid) for the user's unique identifier as opposed to an identity key.

I did not know, thanks for the tip, I will delve into the package.
