### ISSUE TITLE
Unique index's

### ISSUE THREAD

**Issue by brunowego** [gerardmrk/erogen#2]
The [documentation](https://www.postgresql.org/docs/10/indexes-unique.html) give me [some doubts](https://stackoverflow.com/questions/44274080/postgres-hash-index-with-unique-constraint) about hash and unique indexes. I'm get issues running the code:

```sql
CREATE UNIQUE INDEX CONCURRENTLY user_account__username__idx ON identity.user_account USING hash (username);

CREATE UNIQUE INDEX CONCURRENTLY user_account__email_address__idx ON identity.user_account USING hash (email_address);
```

```
error: migration failed: access method "hash" does not support unique indexes in line 0: CREATE UNIQUE INDEX CONCURRENTLY user_account__username__idx ON identity.user_account USING hash (username);

-- CREATE UNIQUE INDEX CONCURRENTLY user_account__email_address__idx ON identity.user_account USING hash (email_address);
 (details: pq: access method "hash" does not support unique indexes)
```

You have some tip for me? Thanks.

**Comment by gerardmrk** [comment]
oh noes forgot to take those 2 out. You can only do uniqueness for b-tree indexes. That said, I mentioned in my last issue none of these will be working yet.. I'm jumping around different directories atm trying to wire things up together conceptually before correcting them.

If you like, I can complete the whole schema for the user service this weekend. I'm taking a break from the `infra/` stuff this week.
