### ISSUE TITLE
DDL Observations

### ISSUE THREAD

**Issue by brunowego** [gerardmrk/erogen#3]
I really like your DDL. 💯

One question, this `CONSTRAINT` are right? Would not be `account_privacy_level`?

https://github.com/gerardmrk/erogen/blob/4493431fba9db325d6d9f488ec800ad6dbaa6a04/svc/user/_migrations_/001.init.up.sql#L229-L230

**Comment by brunowego** [comment]
Plural? `terms_of_services__pk`

https://github.com/gerardmrk/erogen/blob/4493431fba9db325d6d9f488ec800ad6dbaa6a04/svc/user/_migrations_/001.init.up.sql#L198

**Comment by gerardmrk** [comment]
thanks! Yeah to both of them. I'll probably start cleaning up the queries once I finish the frontend app

**Comment by brunowego** [comment]
@gerardmrk are you on in any slack channel?

**Comment by gerardmrk** [comment]
gophers slack yea
